server:
  port: 8080

spring:
  application:
    name: m4-integration-gateway
  cloud:
    gateway:
      routes:
        - id: admin-portal
          uri: http://localhost:8081
          predicates:
            - Path=/api/admin/**
        - id: enforcement-engine
          uri: http://localhost:8083
          predicates:
            - Path=/api/check/**
